### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by slidenerd** [tompiler/candlestick#1]
This code has some serious issues, what is t.rescale inside zoomed function for example

**Comment by tompiler** [comment]
Hi slidenerd,

Welcome to using d3.js! t.rescaleX is the transform.rescaleX function as found in the [d3-zoom](https://github.com/d3/d3-zoom) documentation. 

I don't think the code had any issues at the time of the last commit prior to your message, but I've been tinkering with this anyway so feel free to check out the latest version. 

Thanks!

tompiler
